baseUrl = "https://toylibrarybrightonandhove.org/"
languageCode = "en-gb"
title = "Early Childhood Project Toy Library"

[params]
  # Common Stuff
  copyrightHTML = "&copy; Copyright 2007-2017 <a href=\"https://ecpuk.org\">Brighton, Hove & District Early Childhood Project</a><br/>Registered as a charity in England & Wales, Number 1068309"
  facebookPage = "toylibrarybrightonandhove"

  # Home Page
  coverImage = "/img/iwa0ullrg6g-david-beale_c.jpg"
  coverCredit = "David Beale"
  coverCreditLink = "https://unsplash.com/@davidbeale"
  coverTitle = "The Early Childhood Project Toy Library"
  coverMessage = "A wide selection of carefully chosen resources that reflect family life and diversity and uphold an anti-bias approach to play, care and education for young children, their parents and carers and those working with them in Brighton and Hove."
  aboutTitle = "Who We Are"
  aboutMessage = "We believe that all children have the right to develop in a positive environment free from prejudice and discrimination. The Early Childhood Project, a registered charity, works positively to combat bias of every kind in co-operation with others across Brighton and Hove. We provide information, resources and support to all those people involved in young children’s play, care and education."

  # Contact Details
  addressHTML = "<strong>Early Childhood Project</strong><br>Tarner Children's Centre<br>Ivory Place<br>Brighton, BN2 9QE<br>UNITED KINGDOM"
  phoneNumber = "01273 294105"
  emailAddress = "info@ecpuk.org"

  # Contact Map
  mapCoords = [50.8256, -0.1340]
  mapZoom = 14
  mapToken = "pk.eyJ1IjoiZWNwdWsiLCJhIjoiY2l6bDc5MGRjMDAwYjMycHBna3RndTRyYyJ9.F1-tSNFE1c4GD6BlZYGbaQ"
  mapIcon = "/img/mapMarker.png"
  mapIconSize = [24, 30]
  mapIconAnchor = [12, 30]
